fixed the all the issues and the make it ready for the CR
luck-i/the-NYT-article-in-question pull request #8
Opened 2021-02-19 22:09 UTC by luck-i

i updated the readme file 
fixed the images issues
fixed the icons and reply button
added the submit form with username and email and button to send

2021-02-19 23:34 UTC, smcommits requested changes
# Status: Changes Required 
@luck-i and @work-nadi-altiba Great Job! The page looks great. The clone is fairly close to the original. The Theory of Inflation section is remarkable.

However, a few changes are still required to meet the minimum requirements. 

## Required Changes

- [x] Semantic HTML should be used to structure the page

Please refer [this link](https://www.w3schools.com/html/html5_semantic_elements.asp) to learn more about semantic HTML.

 **For Instance:** In your HTML, you have used `div` element to create a header. Use header element instead.

Please make sure you make use of semantic HTML  throughout your code.

- [x]  The leftmost text on navbar "Space and Cosmos" has to be a link.
- [x]  Don't leave empty `href` attributes in your anchor tags. Instead, add "#"  as a value.
- [ ]  The images and text in the "More Articles" section have to be a link.

## Optional 

- [ ] Please add a folder structure to your project. For example, create an assets folder and place all the images inside of it. Create a CSS folder and place all the CSS files inside of it. 
- [ ] Try to make the PR message and commit messages more descriptive. 

**Once you have implemented the changes, please request another review from your dashboard. Good Luck!**

2021-02-19 23:34 UTC, smcommits commented on stylesheet.css
> +#comment-section > form:nth-child(1) > div:nth-child(1) > h3:nth-child(1) {
When you are using selectors, the longer it is, the higher specificity it will comprise. This can break the CSS cascade and mess up the styles of your site.

This can be avoided by using classes on HTML Elements. Please make your selector short and efficient.

2021-02-20 23:17 UTC, luck-i reviewed
update list :-
1. Semantic HTML is used to structure the page
2. The leftmost text on navbar "Space and Cosmos" has a link.
3. Empty href attributes in your anchor tags. have "#" as a value.
4. The images and text in the "More Articles" section are links now .
5. Added a folder structure to my project. For images , and the style sheet
6. fixed the long css selectors

2021-02-21 01:05 UTC, MarilenaRoque requested changes
## Hello! :rocket:
Congrats on your work on this project, so far. But I can see that some changes required by my teammate were not implemented yet.
Kindly, work on the requirements listed. Below I am leaving more details.

# Changes Required :recycle:

- [ ] Semantic HTML should be used to structure the page
- Use <aside> tag for Editor's picks section on the righmost side. 
- Apply the best practices for semantic HTML.
 > **Why this is important?**  Because it will make it easier to know the purpose of each piece of your page. This is good for machine purposes, like SEO. And also make your code more human-readable, future changes on your page will be made easily.

- [ ] Don't leave empty href attributes in your anchor tags. Instead, add "#" as a value.
- It is standard practice. Please make sure that all your empty href are replaced by "#".

- [ ]  Please add a folder structure to your project. For example, create an assets folder and place all the images inside of it. Create a CSS folder and place all the CSS files inside of it.

- [ ] Try to make the PR message and commit messages more descriptive.

Suggestion:
[OPTIONAL] Your "Inflation Theory" Section is overlapping the navbar when scrolling. You can use **z-index** to fix that behavior.

_Any further questions? Feel free to contact me on Slack._
Happy Coding! 💻 

**_Marilena Roque
Full-Stack Developer
Code Reviewer at Microverse Inc_.**

2021-02-21 01:39 UTC, luck-i reviewed
what is updated :-

- Semantic HTML is used to structure the page
- The leftmost text on navbar "Space and Cosmos" has a link.
- Empty href attributes in your anchor tags. have "#" as a value.
- The images and text in the "More Articles" section are links now .
- Added a folder structure to my project. For images , and the style sheet
- fixed the long css selectors

`fixed the all the issues and the make it ready for the CR` is the branch that i fixed the issues in

2021-02-21 02:25 UTC, krys2fa commented
# Status: Project Approved! 🥇 
Congratulations on making all the requested changes and getting this project approved. 👍 

You can now merge this branch into the main branch and go on with your next project.

💡  Do not forget to submit your project completion form after merging this branch.

All the best @luck-i,
Chris

2021-02-21 02:31 UTC, merged